# Azure Pipelines build script for KeyValues
# installs opam and ocaml from apt, deps from opam, and build with dune

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: | 
    sudo apt install ocaml opam
    opam init -a
  displayName: 'install ocaml and opam'

- script: |
    opam install ocaml-system -y
    opam install angstrom -y
  displayName: 'install opam dependencies'

- script: |
    opam install dune -y
    dune runtest
  displayName: 'run dune tests'
